// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gbinmodkksyuzhekilxb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdiaW5tb2Rra3N5dXpoZWtpbHhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3MjUwMDcsImV4cCI6MjA2NDMwMTAwN30.wWB0M0L9De4M62-tv6axS6oRtTmGZKzGokvWKUV5LiU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});